[package]
name = "image_manager"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
chrono = "0.4.19"
clap = {version = "3.1.6", features = ["derive"]}
config = "0.12.0"
dotenv = "0.15.0"
kamadak-exif = "0.5.4"
regex = "1.5.5"
