version: '3.7'
services:
  postgres:
    build: docker/postgres
    ports:
      - 15432:5432
    environment:
      #POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      #POSTGRES_DB: postgres
      #POSTGRES_PORT: 5432
      #PGSSLMODE: disable
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: image_manager-postgres-data
